apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: 1.16.4
    releaseName: cilium
    namespace: kube-system
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - path: l2-announcement-policy.yaml
  - path: lb-ip-pool.yaml
