apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.19.1
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
    valuesFile: values.yaml

# Additional resources applied after Helm chart
resources:
  - namespace.yaml
  - cluster-issuer-selfsigned.yaml
  - certificate-ingress.yaml
  - cluster-issuer-ingress.yaml
