apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea
  namespace: default
spec:
  subject:
    organizations:
      - example.test
    organizationalUnits:
      - Kubernetes
  commonName: gitea
  dnsNames:
    - gitea.example.test
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 4320h
  secretName: gitea-tls
  issuerRef:
    kind: ClusterIssuer
    name: ingress
