apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - certificate.yaml

helmCharts:
  - name: gitea
    repo: https://dl.gitea.com/charts
    version: 11.0.0
    releaseName: gitea
    namespace: default
    valuesFile: values.yaml
