apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

helmCharts:
  - name: trust-manager
    repo: https://charts.jetstack.io
    version: 0.19.0
    releaseName: trust-manager
    namespace: cert-manager
    valuesFile: values.yaml
