apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

helmCharts:
  - name: jenkins
    repo: https://charts.jenkins.io
    version: 5.8.104
    releaseName: jenkins
    namespace: jenkins
    includeCRDs: true
    valuesFile: values.yaml

# Additional resources applied after Helm chart
resources:
  - namespace.yaml
  - certificate.yaml
