apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: reloader
    repo: https://stakater.github.io/stakater-charts
    version: 1.2.1
    releaseName: reloader
    namespace: kube-system
    valuesFile: values.yaml
