apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server
  namespace: argocd
spec:
  subject:
    organizations:
      - civastack.net
    organizationalUnits:
      - Kubernetes
  commonName: Argo CD Server
  dnsNames:
    - argocd.civastack.net
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 4320h  # 180 days
  secretName: argocd-server-tls
  issuerRef:
    kind: ClusterIssuer
    name: ingress
