apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.0.3
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
    valuesFile: values.yaml

# Additional resources applied after Helm chart
resources:
  - namespace.yaml
  - certificate.yaml
