# ArgoCD Helm values for ArgoCD-managed deployment
# see https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd

global:
  domain: argocd.civastack.net

configs:
  params:
    server.insecure: "true"
    server.repo.server.plaintext: "true"
    server.dex.server.plaintext: "true"
    controller.repo.server.plaintext: "true"
    applicationsetcontroller.repo.server.plaintext: "true"
    reposerver.disable.tls: "true"
    dexserver.disable.tls: "true"
  
  # Configure repository server to enable Helm with Kustomize
  cm:
    kustomize.buildOptions: --enable-helm

server:
  ingress:
    enabled: true
    ingressClassName: cilium
    hostname: argocd.civastack.net
    tls: true
    extraTls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.civastack.net
